#!/usr/bin/env python3
"""Pre-generate natural voice clips for the orthopedic demo with Kokoro-82M (local, Apache-2.0).

Extracts every scripted spoken line from index.html (narrator) and patient.html
(assistant / marcus beats), synthesizes one MP3 per line into assets/audio/, and
writes assets/audio/manifest.js mapping "<role>|<exact text>" -> {f, ms} so
assets/voice.js can play the real clips (it falls back to speechSynthesis for
any text not in the manifest).

Setup (one-time, ~340 MB of model files):
    python3 -m venv tts-env && ./tts-env/bin/pip install kokoro-onnx soundfile
    curl -sLO https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/kokoro-v1.0.onnx
    curl -sLO https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/voices-v1.0.bin

Run (ffmpeg required, `brew install ffmpeg`):
    ./tts-env/bin/python tools/generate_voices.py --model-dir <dir with the two model files>

Change a speaker below in VOICES (voice ids: af_heart, af_bella, af_sarah,
am_michael, am_puck, am_fenrir, ...) and re-run; only stale clips are rebuilt.
"""
import argparse, json, re, subprocess, sys
from pathlib import Path

DEMO = Path(__file__).resolve().parent.parent
AUDIO = DEMO / 'assets' / 'audio'

VOICES = {
    'narrator':  {'voice': 'af_heart',   'speed': 1.06},
    'assistant': {'voice': 'af_bella',   'speed': 1.04},
    'marcus':    {'voice': 'am_michael', 'speed': 1.00},
}
FIRST_NAME = 'Marcus'   # keep in sync with patient.html


def extract_lines():
    """Return ordered [(key, role, text)] for every scripted spoken line."""
    lines = []
    idx = (DEMO / 'index.html').read_text(encoding='utf-8')
    for i, text in enumerate(re.findall(r"speak: '([^']*)'", idx), 1):
        lines.append((f'n{i:02d}', 'narrator', text))

    pat = (DEMO / 'patient.html').read_text(encoding='utf-8')
    beats_src = pat[pat.index('var beats = ['):]
    beats_src = beats_src[:beats_src.index('];')]
    n = 0
    for raw in beats_src.splitlines():
        raw = raw.replace("' + firstName + '", FIRST_NAME)
        m = re.search(r"who: '(\w+)'.*?text: '([^']*)'", raw)
        if m:
            n += 1
            lines.append((f'p{n:02d}-{m.group(1)}', m.group(1), m.group(2)))
    return lines


def synthesize(kokoro, role, text, mp3: Path) -> float:
    """Generate one clip; return duration in seconds."""
    import soundfile as sf
    cfg = VOICES[role]
    samples, sr = kokoro.create(text, voice=cfg['voice'], speed=cfg['speed'], lang='en-us')
    wav = mp3.with_suffix('.wav')
    sf.write(wav, samples, sr)
    subprocess.run(['ffmpeg', '-y', '-loglevel', 'error', '-i', str(wav),
                    '-codec:a', 'libmp3lame', '-b:a', '64k', str(mp3)], check=True)
    wav.unlink()
    return len(samples) / sr


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--model-dir', default='.', help='dir containing kokoro-v1.0.onnx and voices-v1.0.bin')
    ap.add_argument('--check', action='store_true', help='only verify manifest covers every scripted line')
    args = ap.parse_args()

    lines = extract_lines()
    print(f'{len(lines)} scripted lines found')

    if args.check:
        manifest = json.loads(re.search(r'window\.VOICE_CLIPS = (\{.*\});', (AUDIO / 'manifest.js').read_text(encoding='utf-8'), re.S).group(1))
        missing = [k for k, role, text in lines if f'{role}|{text}' not in manifest]
        for k in missing:
            print(f'  MISSING clip for {k}')
        orphans = set(manifest) - {f'{role}|{text}' for _, role, text in lines}
        for o in orphans:
            print(f'  STALE manifest entry: {o[:60]}...')
        sys.exit(1 if missing else 0)

    from kokoro_onnx import Kokoro, EspeakConfig
    md = Path(args.model_dir)
    # espeak-ng truncates its data path at ~160 chars, so the espeakng-loader
    # wheel breaks inside deeply nested venvs — prefer the Homebrew install.
    brew = Path('/opt/homebrew')
    if (brew / 'lib/libespeak-ng.dylib').exists():
        espeak = EspeakConfig(lib_path=str(brew / 'lib/libespeak-ng.dylib'),
                              data_path=str(brew / 'share/espeak-ng-data'))
    else:
        espeak = None   # kokoro falls back to the bundled espeakng-loader wheel
    kokoro = Kokoro(str(md / 'kokoro-v1.0.onnx'), str(md / 'voices-v1.0.bin'), espeak_config=espeak)

    AUDIO.mkdir(parents=True, exist_ok=True)
    manifest = {}
    for key, role, text in lines:
        mp3 = AUDIO / f'{key}.mp3'
        secs = synthesize(kokoro, role, text, mp3)
        manifest[f'{role}|{text}'] = {'f': f'assets/audio/{mp3.name}', 'ms': round(secs * 1000)}
        print(f'  {mp3.name}  {secs:5.1f}s  [{VOICES[role]["voice"]}] {text[:56]}')

    js = json.dumps(manifest, ensure_ascii=True, indent=1)
    (AUDIO / 'manifest.js').write_text(
        '/* generated by tools/generate_voices.py — do not edit by hand */\n'
        f'window.VOICE_CLIPS = {js};\n', encoding='utf-8')
    print(f'wrote {AUDIO / "manifest.js"} ({len(manifest)} clips)')


if __name__ == '__main__':
    main()
